#!/usr/bin/env python3

import os
import shutil
import filecmp
import unittest
import subprocess
from glob import glob


class EmptyValuesTests(unittest.TestCase):
    def test_generate(self):
        EXPECTED = b"Generating scenario's instances:\n0.0 0.0 1000\n    \xe2\x9c\x85 0% empty values 1K members 10 properties\n250.0 0.25 1000\n    \xe2\x9c\x85 25% empty values 1K members 10 properties\n500.0 0.5 1000\n    \xe2\x9c\x85 50% empty values 1K members 10 properties\n750.0 0.75 1000\n    \xe2\x9c\x85 75% empty values 1K members 10 properties\n1000.0 1.0 1000\n    \xe2\x9c\x85 100% empty values 1K members 10 properties\n"
        shutil.rmtree('RMLStreamer', ignore_errors=True)
        CMD = ['../exgentool', '--root', '.', '--scenario',
               'data/tests-empty.json', 'generate']
        output = subprocess.check_output(CMD)
        self.assertEqual(output, EXPECTED)
        for f in glob('RMLStreamer/csv/*/data.csv'):
            result = filecmp.cmp(f,
                                 os.path.join('data', 'tests-empty', f))
            self.assertTrue(result)
        shutil.rmtree('RMLStreamer', ignore_errors=True)

    def test_list(self):
        EXPECTED = b"Scenario's instances:\n     1. 0% empty values 1K members 10 properties\n     2. 25% empty values 1K members 10 properties\n     3. 50% empty values 1K members 10 properties\n     4. 75% empty values 1K members 10 properties\n     5. 100% empty values 1K members 10 properties\n"
        CMD = ['../exgentool', '--root', '.', '--scenario',
               'data/tests-empty.json', 'list']
        output = subprocess.check_output(CMD)
        self.assertEqual(output, EXPECTED)


if __name__ == '__main__':
    unittest.main()
