#!/usr/bin/env python3

import unittest
import subprocess


class UnitTests(unittest.TestCase):
    def test_non_existing_file(self):
        CMD = ['../exgentool', '--root', '.', '--scenario',
               'data/does-not-exist.json', 'list']
        process = subprocess.run(CMD, stdout=subprocess.DEVNULL,
                                 stderr=subprocess.DEVNULL)
        self.assertEqual(process.returncode, 253)


if __name__ == '__main__':
    unittest.main()
