#!/usr/bin/env python3

"""
Template python file to be implemented to run the containerized version of the 
mapping engine.
"""

import os
import psutil
import subprocess
from typing import Optional
from timeout_decorator import timeout, TimeoutError  # type: ignore
from bench_executor.container import Container
from bench_executor.logger import Logger

IMAGE =  "image-name" #TODO: fill in docker image name!
VERSION = '6.2.1' # TODO: fill in version number!
NAME = "engine name" #TODO fill in the engine name!
TIMEOUT = 6 * 3600  # 6 hours

"""TODO: Change the name of the class to match the 'resource' attribute in the metadata.json generated by the 'exgentool'"""
class EngineContainer(Container):
    """Engine container for executing RML mappings."""

    def __init__(self, data_path: str, config_path: str, directory: str,
                 verbose: bool):
        """Creates an instance of the class.

        Parameters
        ----------
        data_path : str
            Path to the data directory of the case.
        config_path : str
            Path to the config directory of the case.
        directory : str
            Path to the directory to store logs.
        verbose : bool
            Enable verbose logs.
        """
        self._data_path = os.path.abspath(data_path)
        self._config_path = os.path.abspath(config_path)
        self._logger = Logger(__name__, directory, verbose)
        self._verbose = verbose
        super().__init__(IMAGE, NAME, self._logger,
                         volumes=[f'{self._data_path}/{NAME}:/data',
                                  f'{self._data_path}/shared:/data/shared'])

    @property
    def root_mount_directory(self) -> str:
        """Subdirectory in the root directory of the case for the engine.

        Returns
        -------
        subdirectory : str
            Subdirectory of the root directory for RMLMapper.

        """
        return __name__.lower()

    @timeout(TIMEOUT)
    def _execute_with_timeout(self, arguments: list) -> bool:
        """Execute a mapping with a provided timeout.

        Returns
        -------
        success : bool
            Whether the execution was successfull or not.
        """
        # Set Java heap to 90% of available memory instead of the default 1/4
        # max_heap = int(psutil.virtual_memory().total * 0.9)

        # Execute command
        cmd = ""
        #cmd = f'java -Xmx{max_heap} -Xms{max_heap}' + \
        #      ' -jar rmlmapper.jar'
        #if self._verbose:
        #    cmd += ' -vvvvvvvvvvvvv'
        #cmd += f' {" ".join(arguments)}'

        self._logger.debug(f'Executing engine with arguments '
                           f'{" ".join(arguments)}')

        exitcode, output = subprocess.getstatusoutput(cmd)
        self._logger.debug(output)
        return exitcode == 0

    def execute(self, arguments: list) -> bool:
        """Execute RMLMapper with given arguments.

        Parameters
        ----------
        arguments : list
            Arguments to supply to RMLMapper.

        Returns
        -------
        success : bool
            Whether the execution succeeded or not.
        """
        try:
            return self._execute_with_timeout(arguments)
        except TimeoutError:
            msg = f'Timeout ({TIMEOUT}s) reached for RMLMapper'
            self._logger.warning(msg)

        return False

    def execute_mapping(self,
                        mapping_file: str,
                        output_file: str,
                        serialization: str ) -> bool:
        """Execute a mapping file with the engine.

        INFO: Don't hestitate to extend the parameters of this function!


        Parameters
        ----------
        mapping_file : str
            Path to the mapping file to execute.
        output_file : str
            Name of the output file to store the triples in.
        serialization : str
            Serialization format to use.

        Returns
        -------
        success : bool
            Whether the execution was successfull or not.
        """
        

        arguments = ['-m', os.path.join('/data/shared/', mapping_file),
                     '-s', serialization,
                     '-o', os.path.join('/data/shared/', output_file),
                     '-d']  # Enable duplicate removal


        return self.execute(arguments)
