#!/usr/bin/python3

from bench_executor.virtuoso import Virtuoso, VERSION

if __name__ == '__main__':
    print(f'ℹ️  Starting up Virtuoso v{VERSION}...')
    v = Virtuoso('data', 'config', 'log', True)
    v.wait_until_ready()
    input('ℹ️  Press any key to stop')
    v.stop()
    print('ℹ️  Stopped')
